CREATE DATABASE Hospital;
USE Hospital;

CREATE TABLE Address(
  ZipCode CHAR(6) NOT NULL,
  Address1 VARCHAR(100) NOT NULL,
  PRIMARY KEY(ZipCode)
);

CREATE TABLE PATIENT(
  Name CHAR(20) NOT NULL,
  ID CHAR(20) NOT NULL AUTO_INCREMENT,
  Sex CHAR(2) NOT NULL,
  ZipCode CHAR(6) NOT NULL,
  Address2 VARCHAR(100) NOT NULL,
  InsuranceCode VARCHAR(30) NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(ZipCode) REFERENCES Address(ZipCode)
      ON UPDATE CASCADE
);

CREATE TABLE DEPARTMENT(
  Department_ID CHAR(20) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20) NOT NULL,
  Place VARCHAR(100) NOT NULL,
  Total_Bed INT(3) NOT NULL,
  Using_Bed INT(3) NOT NULL,
  PRIMARY KEY(Department_ID)
);

CREATE TABLE DOCTOR(
  Name CHAR(20) NOT NULL,
  Employee_ID CHAR(20) NOT NULL AUTO_INCREMENT,
  ID CHAR(20) NOT NULL.
  Employed DATETIME(10) NOT NULL,
  Belong VARCHAR(20) NOT NULL,
  PRIMARY KEY(Employee_ID),
  FOREIGN KEY(Belong) REFERENCES DEPARTMENT(Department_ID)
      ON UPDATE CASCADE
);

ARTER TABLE DEPARTMENT ADD FORIEGN KEY(Manager) REFERENCES DOCTOR(Employee_ID);

CREATE TABLE NURSE(
  Name CHAR(20) NOT NULL,
  Employee_ID CHAR(20) NOT NULL AUTO_INCREMENT,
  ID CHAR(20) NOT NULL.
  Employed DATETIME(10) NOT NULL,
  Belong VARCHAR(20) NOT NULL,
  PRIMARY KEY(Employee_ID),
  FOREIGN KEY(Belong) REFERENCES DEPARTMENT(Department_ID)
      ON UPDATE CASCADE
);


CREATE TABLE HOSPITALIZED(
  Patient_ID CHAR(20) NOT NULL,
  Entered DATETIME(10) NOT NULL,
  Out DATETIME(10) NOT NULL,
  Charged_DR CHAR(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY(Patient_ID, Entered),
  FOREIGN KEY(Charged_DR) REFERENCES DOCTOR(Employee_ID)
      ON UPDATE CASCADE
);

CREATE TABLE TREATMENT(
  Code CHAR(20) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Period CHAR(20) NOT NULL,
  ExpectedResponse VARCHAR(200) NULL,
  Cost INT(10) NOT NULL,
  PRIMARY KEY(Code)
);

CREATE TABLE PatientTreatment(
  Patient CHAR(20) NOT NULL,
  Treatment CHAR(20) NOT NULL,
  PRIMARY KEY(Patient, Treatment),
  FOREIGN KEY(Patient) REFERENCES PATIENT(ID)
      ON UPDATE CASCADE
  FOREIGN KEY(Treatment) REFERENCES TREATMENT(Code)
      ON UPDATE CASCADE
);

CREATE TABLE PatinetNurse(
  Patient CHAR(20) NOT NULL,
  Nurse CHAR(20) NOT NULL,
  FOREIGN KEY(Patient) REFERENCES PATIENT(ID)
      ON UPDATE CASCADE
  FOREIGN KEY(Nurse) REFERENCES NURSE(Employee_ID)
      ON UPDATE CASCADE
);

